---
name: mysql57database
after: databaseconnectors
---
Injector:
  MySQL57Database:
    class: 'MySQL57Database'
    properties:
      connector: %$MySQLiConnector
      schemaManager: %$MySQLSchemaManager
      queryBuilder: %$MySQLQueryBuilder

